name: CI
# this will help you specify where to run 
on:
  push:
    branches:
      - main
# this is where the magic happens, each job happens in parallel btw
jobs:
  build_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    # - uses: actions/setup-node@master
    #   with:
    #    node-version: 16.15.0
    # - name: install node dependencies
    #   run: npm ci
    # - name: build
    #   run: npm run build
    # - name: electron-forge build installer
    #   run: npm run make
    #   echo "git_hash=$git_hash" >> $GITHUB_ENV
    - name: setup artifact
      run: |
        echo ("GIT_HASH=" + $(git rev-parse --short HEAD)) >> $env:GITHUB_ENV
        echo "::set-output name=GIT_HASH::$(git rev-parse --short HEAD)" >> $env:GITHUB_ENV
        echo ("Test: " + ${{ env.GIT_HASH }}
        echo ("ARTIFACT_PATH=${{ github.workspace }}\out\make\squirrel.windows\x64") >> $env:GITHUB_ENV
    - uses: actions/upload-artifact@v3
      with:
        name: twichat-VERSION-${{ env.GIT_HASH }} Setup.exe

        # C:\Users\derek\Documents\Projects\twichat\twichat-ts\out\make\squirrel.windows\x64\twichat-0.1.69 Setup.exe
        path: ${{ env.ARTIFACT_PATH }}\twichat-0.1.69 Setup.exe